import React, { useState, useEffect, useRef } from "react";
import { createPortal } from "react-dom";
import { Folder, FolderOpen, ChevronDown, ChevronRight, Plus, FolderPlus, Trash2, Pencil, FolderInput, ExternalLink, FilePlus, TreePine, EyeOff } from "lucide-react";
import { useWorkspaceStore } from "../store";
import { selectActiveFilePath, selectActiveTabId } from "../store/tabSelectors";
import { fileTabIdentity } from "../tabs/identity";
import { FileIcon } from "../services/fileTypeService";
import { invoke } from "@tauri-apps/api/core";
import { MoveDialog } from "./MoveDialog";
import { CreateDialog } from "./CreateDialog";
import { notify } from "../notificationStore";
import { useConfirm } from "./useConfirm";
import { gitPresenter } from "./git/GitPresenter";
import { resolveRepositoryForPath } from "./git/resolveRepositoryForPath";
import { fileTreePresenter, refreshTree } from "./filetree/FileTreePresenter";

interface FileEntry { name: string; path: string; is_dir: boolean; children?: FileEntry[]; }
interface FileTreeProps { entries: FileEntry[]; }
interface GitState { colorClass: string; char: string; label: string; }
interface ContextMenuState { x: number; y: number; node: any; }
const getGitState = (node: any, status: any): GitState | null => { if (!status) return null; const staged = status.staged.find((f: any) => node.is_dir ? f.path.startsWith(`${node.path}/`) : f.path === node.path); const unstaged = status.unstaged.find((f: any) => node.is_dir ? f.path.startsWith(`${node.path}/`) : f.path === node.path); if (unstaged) return { colorClass: unstaged.status_type === "untracked" ? "text-[var(--color-status-success)]" : "text-[var(--color-status-warning)]", char: unstaged.status_type === "untracked" ? "U" : "M", label: "Modified" }; if (staged) return { colorClass: "text-[var(--color-status-success)]", char: "A", label: "Staged" }; return null; };

export const FileTree: React.FC<FileTreeProps> = ({ entries }) => {
  const [menu, setMenu] = useState<ContextMenuState | null>(null); const [moveNode, setMoveNode] = useState<any>(null); const [renamePath, setRenamePath] = useState<string | null>(null); const [create, setCreate] = useState<{ type: "file" | "folder"; dir: string; name: string } | null>(null); const [selected, setSelected] = useState(new Set<string>()); const [focused, setFocused] = useState<string | null>(null); const ref = useRef<HTMLDivElement>(null); const { confirm, ConfirmModalComponent } = useConfirm();
  const expanded = useWorkspaceStore((state) => state.expandedPaths); const setExpanded = useWorkspaceStore((state) => state.setPathExpanded); const active = useWorkspaceStore(selectActiveFilePath); const reveal = useWorkspaceStore((state) => state.revealFileInTree);
  const open = async (node: FileEntry) => { if (node.path.includes("/.rusty/canvas/") && node.path.endsWith(".json")) { try { const { canvasFileService } = await import("./tabs/canvas/services/canvasFileService"); const data = await canvasFileService.loadCanvasFromFile(node.path); data.id ||= `canvas_${Date.now()}`; useWorkspaceStore.getState().loadCanvasTab(data); } catch (error: any) { notify("Canvas error", `Failed to load canvas: ${error.message || error}`, "error"); } return; } useWorkspaceStore.getState().openTab({ type: "file", path: node.path, title: node.name }); };
  const move = async (paths: string[], dir: string) => { try { for (const path of [...new Set(paths)]) { const name = path.split("/").pop(); if (name && path !== `${dir}/${name}`) await invoke("move_file_or_dir", { src: path, dest: `${dir}/${name}` }); } await refreshTree(); setExpanded(dir, true); setSelected(new Set()); } catch (error) { notify("Move failed", String(error), "error"); } };
  const remove = async (node?: any) => { const paths = node ? (selected.has(node.path) ? [...selected] : [node.path]) : [...selected]; if (!paths.length || !await confirm({ title: "Delete files", message: `Delete ${paths.length} item(s)?`, confirmLabel: "Delete", kind: "danger" })) return; try { await Promise.all(paths.map((path) => invoke("delete_file_or_dir", { path }))); await refreshTree(); setSelected(new Set()); } catch (error) { notify("Delete failed", String(error), "error"); } };
  return <div ref={ref} role="tree" className="space-y-[1px] select-none font-sans text-xs text-[var(--text-normal)] w-full min-h-[300px] overflow-y-auto"><div className="flex items-center justify-between px-2 py-1.5 border-b border-[var(--border-color)] bg-[var(--bg-sidebar)]/50 sticky top-0 z-10"><span className="text-[10px] font-mono text-[var(--text-muted)] uppercase">Files</span><button id="reveal-active-file-btn" onClick={() => active && reveal(active)}><TreePine size={10} /> Reveal</button></div>{entries.map((node) => <TreeNode key={node.path} node={node} expanded={expanded} setExpanded={setExpanded} selected={selected} setSelected={setSelected} focused={focused} setFocused={setFocused} active={active} onOpen={open} onMenu={(event, target) => { event.preventDefault(); setMenu({ x: event.clientX, y: event.clientY, node: target }); }} onMove={move} renamePath={renamePath} setRenamePath={setRenamePath} setCreate={setCreate} />)}{menu && <Menu {...menu} onClose={() => setMenu(null)} onMove={() => { setMoveNode(menu.node); setMenu(null); }} onDelete={() => { void remove(menu.node); setMenu(null); }} onRename={() => { setRenamePath(menu.node.path); setMenu(null); }} onCreate={(type) => { setCreate({ type, dir: menu.node.is_dir ? menu.node.path : menu.node.path.substring(0, menu.node.path.lastIndexOf("/")), name: menu.node.name }); setMenu(null); }} />}{moveNode && <MoveDialog node={moveNode} fileTree={entries} onMove={(destination) => { void move([moveNode.path], destination); setMoveNode(null); }} onCancel={() => setMoveNode(null)} />}{create && <CreateDialog type={create.type} parentDir={create.dir} onCreate={async (name) => { await (create.type === "file" ? fileTreePresenter.createFile(create.dir, name) : fileTreePresenter.createFolder(create.dir, name)); setCreate(null); }} onCancel={() => setCreate(null)} />}{ConfirmModalComponent}</div>;
};

const TreeNode: React.FC<any> = ({ node, expanded, setExpanded, selected, setSelected, focused, setFocused, active, onOpen, onMenu, onMove, renamePath, setRenamePath, setCreate }) => { const [name, setName] = useState(node.name); const input = useRef<HTMLInputElement>(null); const status = useWorkspaceStore((state) => state.gitStatus); const git = getGitState(node, status); const renaming = renamePath === node.path; useEffect(() => { if (renaming) input.current?.focus(); }, [renaming]); const commitRename = async () => { if (name && name !== node.name) await invoke("move_file_or_dir", { src: node.path, dest: `${node.path.substring(0, node.path.lastIndexOf("/"))}/${name}` }); setRenamePath(null); await refreshTree(); }; const click = () => { setFocused(node.path); setSelected(new Set([node.path])); node.is_dir ? setExpanded(node.path, !expanded[node.path]) : void onOpen(node); }; return <div className="w-full"><div data-file-path={node.path} draggable onDragStart={(event) => event.dataTransfer.setData("text/plain", JSON.stringify({ path: node.path, paths: selected.has(node.path) ? [...selected] : [node.path] }))} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); if (node.is_dir) { const data = JSON.parse(event.dataTransfer.getData("text/plain")); void onMove(data.paths || [data.path], node.path); } }} onClick={click} onContextMenu={(event) => onMenu(event, node)} className={`group flex items-center py-1 px-1.5 cursor-pointer border rounded ${selected.has(node.path) ? "bg-[var(--accent-bg)] border-[var(--border-active)]" : "border-transparent hover:bg-[var(--accent-bg)]"} ${focused === node.path ? "ring-1 ring-inset ring-[var(--accent-color)]/60" : ""}`}><span className="mr-1">{node.is_dir ? expanded[node.path] ? <ChevronDown size={13} /> : <ChevronRight size={13} /> : null}</span>{node.is_dir ? expanded[node.path] ? <FolderOpen size={13} /> : <Folder size={13} /> : <FileIcon fileName={node.name} size={13} />}<span className="ml-1 truncate flex-1">{renaming ? <input ref={input} value={name} onChange={(event) => setName(event.target.value)} onBlur={commitRename} onKeyDown={(event) => event.key === "Enter" && void commitRename()} /> : node.name}</span>{git && <span title={git.label} className={git.colorClass}>{git.char}</span>}</div>{node.is_dir && expanded[node.path] && <div className="pl-3 border-l border-[var(--border-color)]/50">{node.children?.map((child: any) => <TreeNode key={child.path} {...{ node: child, expanded, setExpanded, selected, setSelected, focused, setFocused, active, onOpen, onMenu, onMove, renamePath, setRenamePath, setCreate }} />)}</div>}</div>; };
const Menu: React.FC<any> = ({ x, y, onClose, onMove, onDelete, onRename, onCreate }) => createPortal(<div style={{ left: x, top: y }} className="fixed z-[9999] bg-[var(--bg-sidebar)] border border-[var(--border-color)] rounded-lg shadow-2xl py-1 min-w-[160px]">{[[FilePlus, "New File", () => onCreate("file")], [FolderPlus, "New Folder", () => onCreate("folder")], [Pencil, "Rename", onRename], [FolderInput, "Move", onMove], [Trash2, "Delete", onDelete]].map(([Icon, label, action]: any) => <button key={label} onClick={action} className="w-full flex gap-2 px-3 py-2 hover:bg-[var(--accent-bg)]"><Icon size={13} />{label}</button>)}</div>, document.body);
